In [ ]:
# Question 1:
# Write a Python program to convert an array to an ordinary list with the same items.

import numpy as np


myarr = np.array([1, "sh", 4, True])

print(myarr)
print(myarr.dtype)

mylist = myarr.tolist()

print(mylist)
print(type(mylist))


['1' 'sh' '4' 'True']
<U21
['1', 'sh', '4', 'True']
<class 'list'>


In [ ]:
# Question 1:
# Write a Python program to convert an array to an ordinary list with the same items.

import numpy as np

myarr = np.array([1, "sh", 4, True])

mylist = []

for i in myarr:
  mylist.append(i)

print(type(myarr))
print(mylist)
print(type(mylist))

<class 'numpy.ndarray'>
['1', 'sh', '4', 'True']
<class 'list'>


In [ ]:
# Question 2 :
# Write a NumPy program to compute the sum of the diagonal elements of a given array.
# Hint: There are two possible methods to solve this problem: 
# 1 - Manually (without direct function). 2 - Using the trace function

import numpy as np
myarr = np.array([[1,2,3],[4,55,6],[2,30,2]])

print("*my array is ",myarr)

print("* the first way")

dia__of_myarr = np.diagonal(myarr)
print("list of the elements of the diagonal " ,dia__of_myarr)


sum_of_dia = 0
for i in dia__of_myarr:
  sum_of_dia = sum_of_dia + i
  
print("sum of the diagonal is ",sum_of_dia)

print("* the second way ")
trace_myarr = np.trace(myarr)
print("sum of the diagonal is ",trace_myarr)


*my array is  [[ 1  2  3]
 [ 4 55  6]
 [ 2 30  2]]
* the first way
list of the elements of the diagonal  [ 1 55  2]
sum of the diagonal is  58
* the second way 
sum of the diagonal is  58


In [ ]:
# Question 3 :
# Given an array of your choice, get all the values higher than X:
# If a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 

import numpy as np

a = [[1,2],[3,5]]

for i in a:
  for b in i:
    if b > 2:
      print(b)

3
5


In [ ]:
# Question 4 :
# Given two arrays, A & B have the same shape. 
# The task is to apply addition by hand: C is the new array. 

import numpy as np

A = np.array([[20, 30],[15, 4]])

B = np.array([[2,6], [8, 9]])

print("* the first way")

C = A + B
print(C)

print("* the second way")

C = np.add(A,B)
print(C)

* the first way
[[22 36]
 [23 13]]
* the second way
[[22 36]
 [23 13]]


In [ ]:
# Question 5 :
# Write a NumPy program to subtract the mean of each row of a given matrix.
# Hint: use the mean function

import numpy as np

a = np.array([33, 2, 11, 45, 8])

print("* the first way ")
mean_of_a = np.mean(a)
print(mean_of_a)

for i in a:
  sub = i - mean_of_a
  print(sub)

print("* the second way ")
b = a.tolist()
sum = 0
for i in b:
  sum = sum + i
mean_of_b = sum / len(b)
print(mean_of_b)
for i in b:
  sub = i - mean_of_a
  print(sub)

* the first way 
19.8
13.2
-17.8
-8.8
25.2
-11.8
* the second way 
19.8
13.2
-17.8
-8.8
25.2
-11.8
